[build]
  command = "cd apps/web && npm install && npm run build"
  publish = "apps/web/dist"
  environment = { JAVA_VERSION = "11" }

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/antlr-compiler/antlr-4.13.1-complete.jar"]

[dev]
  autoLaunch = false
