[build]
  command = "cd apps/web && npm install && npm run build"
  publish = "apps/web/dist"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/antlr-compiler/antlr-4.13.1-complete.jar"]

[functions."antlr-compiler"]
  image = "netlify/functions/antlr-compiler"

[dev]
  autoLaunch = false
